all: greu


PROG=greu
SRCS=greu.c gre.c
CFLAGS+=-Wall -Werror -fdiagnostics-color -g -Wno-unused-function
MAN=
LDADD=-levent

greu: greu.c gre.h gre.c Makefile.linux
	gcc $(CFLAGS) -o $(PROG) $(SRCS) $(LDADD)

clean:
	rm greu
